# Use the official Python image as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR 'C:\Users\world\OneDrive\Documents\GitHub\L3T23'

# Copy the requirements file into the container at /app
COPY requirements.txt /app/

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code into the container at /app
COPY . /app/

# Define the command to run when the container starts
CMD ["python", "app.py"]
